version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cinema_manager_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
